require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

  # configuration name
project "Flavours", {
  "DebugDev" => :debug,
  "DebugQA" => :debug,
  "DebugProd" => :debug,
  "ReleaseDev" => :release,
  "ReleaseQA" => :release,
  "ReleaseProd" => :release,
  }

target 'Flavours' do
  config = use_native_modules!
  pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'FlavoursTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  use_flipper!(configurations: [‘DebugDev’, ‘DebugQA’,’DebugProd’,’ReleaseDev’,’ReleaseQA’,’ReleaseProd’])


  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
